from pathlib import Path

RANDOM_SEED = 42
INACTIVE_DAYS_CHURN = 90
CHURN_FEATURE_LAG_DAYS = 60
FORECAST_HORIZON_WEEKS = 26
HOLDOUT_WEEKS = 26
TRAIN_TEST_CHURN = 0.25

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
FIGURES_DIR = ARTIFACTS_DIR / "figures"
TABLES_DIR = ARTIFACTS_DIR / "tables"
BI_DIR = ARTIFACTS_DIR / "bi_export"
DASHBOARD_DIR = ARTIFACTS_DIR / "dashboard"
